unbind r
bind r source-file ~/.tmux.conf

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key | splitw -h
bind-key _ splitw -v

set -g allow-passthrough on

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-ghostty:RGB"

set -g status-style "bg=#282828,fg=#ebdbb2"
set -g window-status-style "bg=#282828,fg=#928374"
set -g window-status-current-style "bg=#3c3836,fg=#fe8019,bold"
set -g window-status-activity-style "bg=#282828,fg=#fabd2f,bold"

# Start windows and panes at 1, not 0
# This allows for more ergonomic window switching
set -g base-index 1
setw -g pane-base-index 1
